'use client';

import { useState, useEffect } from 'react';

interface ESGData {
  company_name: string;
  reporting_year: number;
  scope1_tco2e: number;
  scope2_tco2e: number;
  scope3_tco2e?: number;
}

interface Strategies {
  short: string;
  neutral: string;
  detailed: string;
  mode?: string; // 'gemini' or 'mock'
}

interface StrategyGeneratorProps {
  esgData: ESGData | null;
  onStrategySelected?: () => void;
}

type StrategyVariant = 'short' | 'neutral' | 'detailed';

export default function StrategyGenerator({ esgData, onStrategySelected }: StrategyGeneratorProps) {
  const [strategies, setStrategies] = useState<Strategies | null>(null);
  const [selectedVariant, setSelectedVariant] = useState<StrategyVariant | null>(null);
  const [loading, setLoading] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Load saved strategy on mount
  useEffect(() => {
    loadSavedStrategy();
  }, []);

  const loadSavedStrategy = async () => {
    try {
      const response = await fetch('/api/selected-strategy');
      if (response.ok) {
        const data = await response.json();
        if (data) {
          setSelectedVariant(data.variant);
        }
      }
    } catch (error) {
      console.error('Failed to load saved strategy:', error);
    }
  };

  const handleGenerate = async () => {
    if (!esgData) {
      return;
    }

    setLoading(true);
    setStrategies(null);
    setSelectedVariant(null);

    console.log('%c🤖 Generating ESG Strategies...', 'color: #10b981; font-weight: bold; font-size: 14px');
    console.log('Company:', esgData.company_name);
    console.log('Year:', esgData.reporting_year);

    try {
      const response = await fetch('/api/generate-strategy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(esgData),
      });

      if (response.ok) {
        const data = await response.json();
        setStrategies(data);
        
        console.log('%c✅ Strategies Generated!', 'color: #10b981; font-weight: bold; font-size: 14px');
        console.log('Mode:', data.mode === 'gemini' ? '🤖 AI (Gemini)' : '📝 Mock');
        console.log('Short:', data.short?.substring(0, 100) + '...');
        console.log('Neutral:', data.neutral?.substring(0, 100) + '...');
        console.log('Detailed:', data.detailed?.substring(0, 100) + '...');
      } else {
        console.error('Failed to generate strategies');
      }
    } catch (error) {
      console.error('Error generating strategies:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSelect = async (variant: StrategyVariant) => {
    if (!strategies) return;

    setSelectedVariant(variant);
    setSaveSuccess(false);

    try {
      const response = await fetch('/api/selected-strategy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          variant,
          content: strategies[variant],
        }),
      });

      if (response.ok) {
        setSaveSuccess(true);
        setTimeout(() => setSaveSuccess(false), 3000);
        // Notify parent component
        if (onStrategySelected) {
          onStrategySelected();
        }
      }
    } catch (error) {
      console.error('Error saving selection:', error);
    }
  };

  const variantLabels = {
    short: 'Short (2-4 sentences)',
    neutral: 'Neutral (5-8 sentences)',
    detailed: 'Detailed (structured with measures)',
  };

  if (!esgData) {
    return (
      <div className="w-full p-6 bg-white rounded-lg shadow-lg">
        <h3 className="text-xl font-semibold mb-4 text-gray-800">Strategy Generation</h3>
        <div className="text-gray-500 text-center py-8">
          Please save ESG data first to generate strategies.
        </div>
      </div>
    );
  }

  return (
    <div className="w-full p-6 bg-white rounded-lg shadow-lg">
      <h3 className="text-xl font-semibold mb-4 text-gray-800">AI Strategy Generation</h3>

      {/* Generate Button */}
      <button
        onClick={handleGenerate}
        disabled={loading}
        className="w-full mb-6 bg-green-600 text-white py-3 px-4 rounded-md hover:bg-green-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors font-medium"
      >
        {loading ? 'Generating Strategies...' : '🤖 Generate ESG Strategies'}
      </button>

      {/* AI Mode Badge - Only show when using Gemini */}
      {strategies && strategies.mode === 'gemini' && (
        <div className="mb-4 flex items-center gap-2">
          <div className="flex items-center gap-2 px-3 py-1.5 bg-purple-100 border border-purple-300 rounded-full">
            <span className="text-purple-700 font-semibold text-sm">✨ Generated by AI</span>
            <span className="text-xs text-purple-600">(Google Gemini)</span>
          </div>
        </div>
      )}

      {/* Strategy Variants */}
      {strategies && (
        <div className="space-y-4">
          {(Object.keys(strategies).filter(key => key !== 'mode') as StrategyVariant[]).map((variant) => (
            <div
              key={variant}
              className={`border-2 rounded-lg p-4 transition-all cursor-pointer ${
                selectedVariant === variant
                  ? 'border-green-500 bg-green-50'
                  : 'border-gray-200 hover:border-gray-300'
              }`}
              onClick={() => handleSelect(variant)}
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex items-center gap-2">
                  <input
                    type="radio"
                    checked={selectedVariant === variant}
                    onChange={() => handleSelect(variant)}
                    className="mt-1"
                  />
                  <h4 className="font-semibold text-gray-800">
                    {variantLabels[variant]}
                  </h4>
                </div>
                {selectedVariant === variant && (
                  <span className="text-xs bg-green-600 text-white px-2 py-1 rounded">
                    Selected
                  </span>
                )}
              </div>
              <div className="ml-6 text-sm text-gray-700 whitespace-pre-wrap">
                {strategies[variant]}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Success Message */}
      {saveSuccess && (
        <div className="mt-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded-md">
          ✓ Strategy selection saved successfully!
        </div>
      )}

      {/* Info */}
      {!strategies && !loading && (
        <div className="text-sm text-gray-500 text-center">
          Click the button above to generate three strategy variants based on your ESG data.
          You can then select one to save.
        </div>
      )}
    </div>
  );
}
